In [1]:
from pykrx import stock

In [2]:
tickers = stock.get_index_ticker_list(market="KOSPI")

In [3]:
for ticker in tickers:
    tickerName = stock.get_index_ticker_name(ticker)
    print(ticker, tickerName)

1001 코스피
1002 코스피 대형주
1003 코스피 중형주
1004 코스피 소형주
1005 음식료품
1006 섬유의복
1007 종이목재
1008 화학
1009 의약품
1010 비금속광물
1011 철강금속
1012 기계
1013 전기전자
1014 의료정밀
1015 운수장비
1016 유통업
1017 전기가스업
1018 건설업
1019 운수창고업
1020 통신업
1021 금융업
1022
1024 증권
1025 보험
1026 서비스업
1027 제조업
1028 코스피 200
1034 코스피 100
1035 코스피 50
1150 코스피 200 커뮤니케이션서비스
1151 코스피 200 건설
1152 코스피 200 중공업
1153 코스피 200 철강/소재
1154 코스피 200 에너지/화학
1155 코스피 200 정보기술
1156 코스피 200 금융
1157 코스피 200 생활소비재
1158 코스피 200 경기소비재
1159 코스피 200 산업재
1160 코스피 200 헬스케어
1167 코스피 200 중소형주
1182 코스피 200 초대형제외 지수
1224 코스피 200 비중상한 30%
1227 코스피 200 비중상한 25%
1232 코스피 200 비중상한 20%
1244 코스피200제외 코스피지수
1894 코스피 200 TOP 10

In [4]:
df = stock.get_index_ohlcv_by_date(fromdate="20220105", todate="20221130", ticker="1155")

In [5]:
df

코스피 200 정보기술,시가,고가,저가,종가,거래량,거래대금,상장시가총액
날짜,,,,,,,
2022-01-05,3802.77,3810.73,3694.92,3742.70,50106295,4294849393200,715791095475000
2022-01-06,3690.86,3743.82,3659.93,3674.76,31940189,2769979938340,707923737418000
2022-01-07,3708.26,3748.30,3707.90,3721.59,30550581,2871614607719,719173033896500
2022-01-10,3700.35,3701.03,3623.30,3642.13,23960283,2243955314068,711126817448900
2022-01-11,3662.93,3686.18,3640.79,3677.04,28200917,2512385056789,719171321132700
...,...,...,...,...,...,...,...
2022-11-24,2935.95,2946.46,2914.33,2943.76,13798169,1049333386788,557355216759150
2022-11-25,2943.38,2945.81,2923.47,2929.94,11397364,893671989292,553632856465000
2022-11-28,2915.03,2924.16,2884.80,2909.55,16554918,1243662610800,546618891669150
2022-11-29,2897.18,2914.25,2881.33,2913.00,12087284,908078376773,549845299143050
2022-11-30,2898.55,2969.77,2887.28,2969.77,33059100,2428942171046,562599869991950

In [6]:
df = df['종가'].pct_change().dropna()

In [7]:
df.to_csv('코스피200_정보기술_일별.csv', encoding='utf-8-sig')